function Resetting() {
  return (
    <>
      <h2>Resetting Your Project</h2>
      <p>
        At any time, all of the files generated by PyPI Maker can be removed
        with the following command:
      </p>
      <code>pypimaker reset</code>
    </>
  );
}

export default Resetting;
